cloud:
  aws:
    s3:
      bucket: swyg-picket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA3RTEIKP5OJMLLRWM
      secretKey: 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
